# Generated by Django 3.2.18 on 2023-05-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blood', '0005_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='name',
            field=models.CharField(max_length=70),
        ),
    ]
