name: Build and Deploy Docker Image to GCR

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: 'auth'
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}

    - name: 'Set up Cloud SDK'
      uses: google-github-actions/setup-gcloud@v1

    - name: 'Use gcloud CLI'
      run: gcloud info

    - name: Configure Docker
      run: |
       docker login --username=mugumbyabenon --password=@Kibuuka1

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        dockerfile: Dockerfile
        push: true
        tags: mugumbyabenon/bloodmanagementsystem:background
