name: Build and Deploy Docker Image to GCR

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: makereremanifest
        service_account_email: demo-950@makereremanifest.iam.gserviceaccount.com
        service_account_key: ${{ secrets.SERVICE_ACCOUNT_KEY }}

    #- name: Configure Docker
     # run: |
      #  echo ${{ secrets.SERVICE_ACCOUNT_KEY }} | base64 --decode > /tmp/gcp-sa-key.json
       # docker login -u _json_key --password-stdin https://gcr.io < /tmp/gcp-sa-key.json

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        dockerfile: Dockerfile
        push: true
        tags: gcr.io/makereremanifest/bloodmanagementsystem:latest
